//main page products
export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

//explore page products
export const FETCH_EXPLORE_START = "FETCH_EXPLORE_START";
export const FETCH_EXPLORE_SUCCESS = "FETCH_EXPLORE_SUCCESS";
export const FETCH_EXPLORE_FAILURE = "FETCH_EXPLORE_FAILURE";

//single product
export const FETCH_SINGLE_PRODUCT_START = "FETCH_SINGLE_PRODUCT_START";
export const FETCH_SINGLE_PRODUCT_SUCCESS = "FETCH_SINGLE_PRODUCT_SUCCESS";
export const FETCH_SINGLE_PRODUCT_FAILURE = "FETCH_SINGLE_PRODUCT_FAILURE";

//main product
export const FETCH_MAIN_PRODUCT_START = "FETCH_MAIN_PRODUCT_START";
export const FETCH_MAIN_PRODUCT_SUCCESS = "FETCH_MAIN_PRODUCT_SUCCESS";
export const FETCH_MAIN_PRODUCT_FAILURE = "FETCH_MAIN_PRODUCT_FAILURE";

//search query
export const FETCH_QUERY_START = "FETCH_QUERY_START";
export const FETCH_QUERY_SUCCESS = "FETCH_QUERY_SUCCESS";
export const FETCH_QUERY_FAILURE = "FETCH_QUERY_FAILURE";

//is logged in
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
